# Generated by Django 5.1.3 on 2024-11-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_availablesession_bookedsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='session_link',
            field=models.URLField(blank=True, help_text='Link to the session for confirmed bookings', null=True),
        ),
    ]
