# Generated by Django 5.1.3 on 2024-11-14 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bookedsession_session_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating out of 5', max_digits=3),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating out of 5, where 5 is excellent')),
                ('review', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('booked_session', models.OneToOneField(help_text='The session for which feedback is provided', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='users.bookedsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to=settings.AUTH_USER_MODEL)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.tutorprofile')),
            ],
        ),
    ]
